package ink.icoding.smartmybatis.mapper.provider;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;
import java.util.UUID;

import junit.framework.TestCase;
import org.apache.ibatis.datasource.unpooled.UnpooledDataSource;
import org.apache.ibatis.mapping.Environment;
import org.apache.ibatis.session.Configuration;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.apache.ibatis.transaction.jdbc.JdbcTransactionFactory;

import ink.icoding.smartmybatis.conf.GlobalConfig;
import ink.icoding.smartmybatis.conf.NamingConvention;
import ink.icoding.smartmybatis.conf.SmartConfigHolder;
import ink.icoding.smartmybatis.entity.po.PO;
import ink.icoding.smartmybatis.entity.po.enums.ID;
import ink.icoding.smartmybatis.entity.po.enums.PrimaryGenerateType;
import ink.icoding.smartmybatis.entity.po.enums.TableName;
import ink.icoding.smartmybatis.mapper.base.SmartMapper;
import ink.icoding.smartmybatis.mapper.provider.dialects.SqlDialects;
import ink.icoding.smartmybatis.mapper.provider.dialects.impl.H2Dialect;

/** Runs inherited SmartMapper inserts against H2, without custom SQL Providers. */
public class BaseSqlProviderInputKeyTest extends TestCase {
    private GlobalConfig previousConfig;
    private SqlDialects previousDialect;
    private GlobalConfig config;
    private SqlSession session;
    private InputMapper mapper;

    @Override
    protected void setUp() throws Exception {
        previousConfig = SmartConfigHolder.config();
        previousDialect = SmartConfigHolder.getDialect();
        config = new GlobalConfig();
        config.setNamingConvention(NamingConvention.UNDERLINE_LOWER);
        SmartConfigHolder.init(config, new H2Dialect());
        UnpooledDataSource source = new UnpooledDataSource("org.h2.Driver",
                "jdbc:h2:mem:input_key_" + UUID.randomUUID(), "sa", "");
        Configuration mybatis = new Configuration(new Environment("test",
                new JdbcTransactionFactory(), source));
        mybatis.addMapper(InputMapper.class);
        mybatis.addMapper(NumericMapper.class);
        mybatis.addMapper(UuidMapper.class);
        mybatis.addMapper(AutoMapper.class);
        mybatis.addMapper(SnowflakeMapper.class);
        mybatis.addMapper(HexMapper.class);
        session = new SqlSessionFactoryBuilder().build(mybatis).openSession(true);
        mapper = session.getMapper(InputMapper.class);
        try (Statement sql = session.getConnection().createStatement()) {
            for (String name : Arrays.asList("input_records", "uuid_records", "snowflake_records", "hex_records")) {
                sql.execute("CREATE TABLE \"" + name + "\" (\"id\" VARCHAR(255) PRIMARY KEY, \"label\" VARCHAR(255))");
            }
            sql.execute("CREATE TABLE \"numeric_records\" (\"id\" BIGINT PRIMARY KEY, \"label\" VARCHAR(255))");
            sql.execute("CREATE TABLE \"auto_records\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"label\" VARCHAR(255))");
        }
    }

    @Override
    protected void tearDown() {
        if (session != null) session.close();
        SmartConfigHolder.init(previousConfig, previousDialect);
    }

    public void testDefaultSingleInsertPreservesCallerKeyAndDatabaseIdentity() {
        assertTrue(config.isPreserveInputPrimaryKey());
        InputRecord record = input("binding-fixed-id");
        assertEquals(1, mapper.insert(record));
        assertEquals("binding-fixed-id", record.getId());
        assertEquals("binding-fixed-id", mapper.selectById("binding-fixed-id").getId());
    }

    public void testDefaultBatchInsertPreservesEveryCallerKey() {
        InputRecord first = input("fixed-1"), second = input("fixed-2");
        assertEquals(2, mapper.insertBatch(Arrays.asList(first, second)));
        assertEquals("fixed-1", first.getId());
        assertEquals("fixed-2", second.getId());
        assertNotNull(mapper.selectById("fixed-1"));
        assertNotNull(mapper.selectById("fixed-2"));
    }

    public void testLegacySingleInsertExplicitlyReplacesCallerKeyWithUuid() {
        config.setPreserveInputPrimaryKey(false);
        InputRecord record = input("legacy-key");
        mapper.insert(record);
        assertTrue(record.getId().matches("[0-9a-f]{32}"));
        assertNull(mapper.selectById("legacy-key"));
        assertNotNull(mapper.selectById(record.getId()));
    }

    public void testLegacyBatchInsertReplacesEveryCallerKeyWithDistinctUuid() {
        config.setPreserveInputPrimaryKey(false);
        InputRecord first = input("legacy-1"), second = input("legacy-2");
        assertEquals(2, mapper.insertBatch(Arrays.asList(first, second)));
        assertTrue(first.getId().matches("[0-9a-f]{32}"));
        assertTrue(second.getId().matches("[0-9a-f]{32}"));
        assertFalse(first.getId().equals(second.getId()));
        assertNotNull(mapper.selectById(first.getId()));
        assertNotNull(mapper.selectById(second.getId()));
    }

    public void testNullInputKeyIsRejectedInBothModes() {
        for (boolean preserve : new boolean[] {true, false}) {
            config.setPreserveInputPrimaryKey(preserve);
            assertMissingInput(() -> mapper.insert(input(null)));
        }
        assertEquals(0L, mapper.count());
    }

    public void testNullBatchInputKeyIsRejectedWithoutInsertingAnyRows() {
        InputRecord valid = input("fixed-batch-id");
        assertMissingInput(() -> mapper.insertBatch(Arrays.asList(valid, input(null))));
        assertEquals("fixed-batch-id", valid.getId());
        assertEquals(0L, mapper.count());
    }

    public void testNumericInputKeyIsPreservedWithoutConvertingItToUuid() {
        NumericRecord record = new NumericRecord();
        record.setId(42L);
        record.setLabel("numeric");
        NumericMapper numeric = session.getMapper(NumericMapper.class);
        assertEquals(1, numeric.insert(record));
        assertEquals(Long.valueOf(42), record.getId());
        assertEquals(Long.valueOf(42), numeric.selectById(42L).getId());
    }

    public void testUuidStrategyStillGeneratesKeysInBothModes() {
        for (boolean preserve : new boolean[] {true, false}) {
            config.setPreserveInputPrimaryKey(preserve);
            UuidRecord record = new UuidRecord();
            record.setId("preexisting-uuid-key");
            record.setLabel("uuid");
            UuidMapper uuid = session.getMapper(UuidMapper.class);
            uuid.insert(record);
            assertTrue(record.getId().matches("[0-9a-f]{32}"));
            assertNotNull(uuid.selectById(record.getId()));
        }
    }

    public void testAutoStrategyStillUsesDatabaseIdentityInBothModes() throws Exception {
        for (boolean preserve : new boolean[] {true, false}) {
            config.setPreserveInputPrimaryKey(preserve);
            AutoRecord record = new AutoRecord();
            record.setLabel("auto");
            assertEquals(1, session.getMapper(AutoMapper.class).insert(record));
        }
        try (Statement sql = session.getConnection().createStatement();
                ResultSet rows = sql.executeQuery("SELECT COUNT(*) FROM \"auto_records\" WHERE \"id\" IS NOT NULL")) {
            assertTrue(rows.next());
            assertEquals(2, rows.getInt(1));
        }
    }

    public void testSnowflakeStrategiesStillGenerateKeysInBothModes() {
        for (boolean preserve : new boolean[] {true, false}) {
            config.setPreserveInputPrimaryKey(preserve);
            SnowflakeRecord record = new SnowflakeRecord();
            record.setId("preexisting-key");
            record.setLabel("snowflake");
            SnowflakeMapper snowflake = session.getMapper(SnowflakeMapper.class);
            snowflake.insert(record);
            assertTrue(record.getId().matches("[0-9]+"));
            assertNotNull(snowflake.selectById(record.getId()));
            HexRecord hex = new HexRecord();
            hex.setId("preexisting-key");
            hex.setLabel("hex");
            HexMapper hexMapper = session.getMapper(HexMapper.class);
            hexMapper.insert(hex);
            assertTrue(hex.getId().matches("[0-9a-f]+"));
            assertNotNull(hexMapper.selectById(hex.getId()));
        }
    }

    private InputRecord input(String id) {
        InputRecord record = new InputRecord();
        record.setId(id);
        record.setLabel("test");
        return record;
    }

    private void assertMissingInput(Runnable action) {
        try {
            action.run();
            fail("Null INPUT key must fail before SQL execution");
        } catch (RuntimeException error) {
            Throwable cause = error;
            while (cause != null && !(cause instanceof IllegalArgumentException)) cause = cause.getCause();
            assertNotNull("Expected INPUT validation error", cause);
            assertTrue(cause.getMessage().contains("INPUT"));
        }
    }

    @TableName("input_records")
    public static class InputRecord extends PO {
        @ID(generateType = PrimaryGenerateType.INPUT)
        private String id;
        private String label;
        public String getId() { return id; }
        public void setId(String id) { this.id = id; }
        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }
    }

    @TableName("numeric_records")
    public static class NumericRecord extends PO {
        @ID(generateType = PrimaryGenerateType.INPUT)
        private Long id;
        private String label;
        public Long getId() { return id; }
        public void setId(Long id) { this.id = id; }
        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }
    }

    @TableName("uuid_records")
    public static class UuidRecord extends PO {
        @ID(generateType = PrimaryGenerateType.UUID)
        private String id;
        private String label;
        public String getId() { return id; }
        public void setId(String id) { this.id = id; }
        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }
    }

    @TableName("auto_records")
    public static class AutoRecord extends PO {
        @ID(generateType = PrimaryGenerateType.AUTO)
        private Long id;
        private String label;
        public Long getId() { return id; }
        public void setId(Long id) { this.id = id; }
        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }
    }

    @TableName("snowflake_records")
    public static class SnowflakeRecord extends PO {
        @ID(generateType = PrimaryGenerateType.SNOWFLAKE)
        private String id;
        private String label;
        public String getId() { return id; }
        public void setId(String id) { this.id = id; }
        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }
    }

    @TableName("hex_records")
    public static class HexRecord extends PO {
        @ID(generateType = PrimaryGenerateType.SNOWFLAKE_HEX)
        private String id;
        private String label;
        public String getId() { return id; }
        public void setId(String id) { this.id = id; }
        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }
    }

    public interface InputMapper extends SmartMapper<InputRecord> {}
    public interface NumericMapper extends SmartMapper<NumericRecord> {}
    public interface UuidMapper extends SmartMapper<UuidRecord> {}
    public interface AutoMapper extends SmartMapper<AutoRecord> {}
    public interface SnowflakeMapper extends SmartMapper<SnowflakeRecord> {}
    public interface HexMapper extends SmartMapper<HexRecord> {}
}
